Update deploy-pipelines.yml for Azure Pipelines

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -172,20 +172,24 @@ stages:
     jobs:
       - job: 'do_healthcheck'
         steps:
-          - task: Bash@3
-            inputs:
-              targetType: 'inline'
-              script: |
-                OUTPUT_REST = $(az rest --skip-authorization-header --method get --url "https://$(host)/$(APIM_BASEPATH)/info")
-                echo ${OUTPUT_REST}
-                # check if rest response contains app-name
-                if [[ ${OUTPUT_REST} == *$(imageRepository)* ]]; then
-                  echo "responseCheckString: '$(imageRepository)' found, continue"
-                  exit 0
-                else
-                  echo "responseCheckString: '$(imageRepository)' not found, fail"
-                  exit 1
-                fi
+        - task: AzureCLI@2
+          inputs:
+            azureSubscription: '$(kubernetesServiceConnection)'
+            scriptType: 'batch'
+            failOnStandardError: false
+            scriptLocation: 'inlineScript'
+            inlineScript: |
+              OUTPUT_REST = $(az rest --skip-authorization-header --method get --url "https://$(host)/$(APIM_BASEPATH)/info")
+              echo ${OUTPUT_REST}
+              # check if rest response contains app-name
+              if [[ ${OUTPUT_REST} == *$(imageRepository)* ]]; then
+                echo "responseCheckString: '$(imageRepository)' found, continue"
+                exit 0
+              else
+                echo "responseCheckString: '$(imageRepository)' not found, fail"
+                exit 1
+              fi
+       
 
   # Run Integration Tests
   - stage: Test
